object Modules {
    const val app = ":app"

    const val core = ":core"
    const val coreUi = ":core_ui"

    const val authData = ":data:auth_data"
    const val feedData = ":data:feed_data"
    const val locationData = ":data:location_data"
    const val merchantData = ":data:merchant_data"
    const val orderData = ":data:order_data"
    const val productData = ":data:product_data"
    const val userData = ":data:user_data"

    const val authDomain = ":domain:auth_domain"
    const val feedDomain = ":domain:feed_domain"
    const val locationDomain = ":domain:location_domain"
    const val merchantDomain = ":domain:merchant_domain"
    const val orderDomain = ":domain:order_domain"
    const val productDomain = ":domain:product_domain"
    const val userDomain = ":domain:user_domain"

    const val addFeed = ":presentation:add_feed"
    const val addMenu = ":presentation:add_menu"
    const val addReview = ":presentation:add_review"
    const val editProfile = ":presentation:edit_profile"
    const val forgetPassword = ":presentation:forget_password"
    const val home = ":presentation:home"
    const val login = ":presentation:login"
    const val merchantProfile = ":presentation:merchant_profile"
    const val otherProfile = ":presentation:other_profile"
    const val profile = ":presentation:profile"
    const val profileSetting = ":presentation:profile_setting"
    const val registerMerchant = ":presentation:register_merchant"
    const val search = ":presentation:search"
    const val signUp = ":presentation:sign_up"
    const val singleFeed = ":presentation:single_feed"
}